packages:
  core: !include guition-esp32-s3-4848s040.yaml

esphome:
  project:
    name: wonderslug.media-player
    version: dev

dashboard_import:
  package_import_url: github://wonderslug/esphome-media-player/devices/guition-esp32-s3-4848s040/esphome.yaml@main

improv_serial:
